# nixpacks.toml

[phases.setup]
# A comprehensive list of system packages for headless Chrome
pkgs = [
  "pkgs.chromedriver",
  "pkgs.chromium",
  "pkgs.alsa-lib",
  "pkgs.at-spi2-atk",
  "pkgs.cups",
  "pkgs.gconf",
  "pkgs.gtk3",
  "pkgs.libx11",
  "pkgs.libxss",
  "pkgs.libxtst",
  "pkgs.nss"
]